### /register

POST http://localhost:3000/register
Content-Type: application/json

{
  "email": "test",
  "password": "test"
}

### Store the token from the response
# token = response.body.token

### /home

GET http://localhost:3000/home


###
GET http://localhost:3000/logout

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "brandon28davidson@gmail.com",
  "password": "123"
}

###
# token = response.body.token

# Step 2: Create a budget using the obtained token
GET http://localhost:3000/budget/64d7e0d17802773c9243f30d
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJyYW5kb24yOGRhdmlkc29uQGdtYWlsLmNvbSIsImlhdCI6MTY5MTg3OTM2Nn0.gaJAENyHeFqjMlFYvbray4A8oCWw5vDcfIeOnEZXTBQ


###
POST http://localhost:3000/budget/64d7e0d17802773c9243f30d
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJyYW5kb24yOGRhdmlkc29uQGdtYWlsLmNvbSIsImlhdCI6MTY5MTg5NTU2NX0.McSc4mAEbRK3oSylS7WZbp_F_0VFRqUgVlSy-lNnkwU

{
  "name":"b",
  "category":"Income",
  "amount":"1"
}



